---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: ensure apache is stopped
    service: name=httpd state=stopped enabled=no    
  - name: ensure apache is deinstalled
    yum: name=httpd state=absent

...
